/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPosterGenRouteImport } from './routes/_app/poster-gen'
import { Route as AppFacesimRouteImport } from './routes/_app/facesim'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'
import { Route as AppAdminIndexRouteImport } from './routes/_app/admin/index'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminStatsRouteImport } from './routes/_app/admin/stats'
import { Route as AppAdminProvidersRouteImport } from './routes/_app/admin/providers'
import { Route as AppAdminModelsRouteImport } from './routes/_app/admin/models'
import { Route as AppAdminMedicalAestheticsRouteImport } from './routes/_app/admin/medical-aesthetics'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPosterGenRoute = AppPosterGenRouteImport.update({
  id: '/poster-gen',
  path: '/poster-gen',
  getParentRoute: () => AppRoute,
} as any)
const AppFacesimRoute = AppFacesimRouteImport.update({
  id: '/facesim',
  path: '/facesim',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminStatsRoute = AppAdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminProvidersRoute = AppAdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminModelsRoute = AppAdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMedicalAestheticsRoute =
  AppAdminMedicalAestheticsRouteImport.update({
    id: '/medical-aesthetics',
    path: '/medical-aesthetics',
    getParentRoute: () => AppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/chat': typeof AppChatRoute
  '/facesim': typeof AppFacesimRoute
  '/poster-gen': typeof AppPosterGenRoute
  '/admin/medical-aesthetics': typeof AppAdminMedicalAestheticsRoute
  '/admin/models': typeof AppAdminModelsRoute
  '/admin/providers': typeof AppAdminProvidersRoute
  '/admin/stats': typeof AppAdminStatsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin/': typeof AppAdminIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRoute
  '/facesim': typeof AppFacesimRoute
  '/poster-gen': typeof AppPosterGenRoute
  '/admin/medical-aesthetics': typeof AppAdminMedicalAestheticsRoute
  '/admin/models': typeof AppAdminModelsRoute
  '/admin/providers': typeof AppAdminProvidersRoute
  '/admin/stats': typeof AppAdminStatsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/admin': typeof AppAdminIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/facesim': typeof AppFacesimRoute
  '/_app/poster-gen': typeof AppPosterGenRoute
  '/_app/admin/medical-aesthetics': typeof AppAdminMedicalAestheticsRoute
  '/_app/admin/models': typeof AppAdminModelsRoute
  '/_app/admin/providers': typeof AppAdminProvidersRoute
  '/_app/admin/stats': typeof AppAdminStatsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/chat'
    | '/facesim'
    | '/poster-gen'
    | '/admin/medical-aesthetics'
    | '/admin/models'
    | '/admin/providers'
    | '/admin/stats'
    | '/admin/users'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chat'
    | '/facesim'
    | '/poster-gen'
    | '/admin/medical-aesthetics'
    | '/admin/models'
    | '/admin/providers'
    | '/admin/stats'
    | '/admin/users'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/chat'
    | '/_app/facesim'
    | '/_app/poster-gen'
    | '/_app/admin/medical-aesthetics'
    | '/_app/admin/models'
    | '/_app/admin/providers'
    | '/_app/admin/stats'
    | '/_app/admin/users'
    | '/_app/admin/'
    | '/_app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/poster-gen': {
      id: '/_app/poster-gen'
      path: '/poster-gen'
      fullPath: '/poster-gen'
      preLoaderRoute: typeof AppPosterGenRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facesim': {
      id: '/_app/facesim'
      path: '/facesim'
      fullPath: '/facesim'
      preLoaderRoute: typeof AppFacesimRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/stats': {
      id: '/_app/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AppAdminStatsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/providers': {
      id: '/_app/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AppAdminProvidersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/models': {
      id: '/_app/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AppAdminModelsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/medical-aesthetics': {
      id: '/_app/admin/medical-aesthetics'
      path: '/medical-aesthetics'
      fullPath: '/admin/medical-aesthetics'
      preLoaderRoute: typeof AppAdminMedicalAestheticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminMedicalAestheticsRoute: typeof AppAdminMedicalAestheticsRoute
  AppAdminModelsRoute: typeof AppAdminModelsRoute
  AppAdminProvidersRoute: typeof AppAdminProvidersRoute
  AppAdminStatsRoute: typeof AppAdminStatsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminMedicalAestheticsRoute: AppAdminMedicalAestheticsRoute,
  AppAdminModelsRoute: AppAdminModelsRoute,
  AppAdminProvidersRoute: AppAdminProvidersRoute,
  AppAdminStatsRoute: AppAdminStatsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppChatRoute: typeof AppChatRoute
  AppFacesimRoute: typeof AppFacesimRoute
  AppPosterGenRoute: typeof AppPosterGenRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppChatRoute: AppChatRoute,
  AppFacesimRoute: AppFacesimRoute,
  AppPosterGenRoute: AppPosterGenRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
