/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PosterGenRouteImport } from './routes/poster-gen'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacesimRouteImport } from './routes/facesim'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminStatsRouteImport } from './routes/admin/stats'
import { Route as AdminProvidersRouteImport } from './routes/admin/providers'
import { Route as AdminModelsRouteImport } from './routes/admin/models'
import { Route as AdminMedicalAestheticsRouteImport } from './routes/admin/medical-aesthetics'

const PosterGenRoute = PosterGenRouteImport.update({
  id: '/poster-gen',
  path: '/poster-gen',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacesimRoute = FacesimRouteImport.update({
  id: '/facesim',
  path: '/facesim',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/dashboard/chat',
  path: '/dashboard/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStatsRoute = AdminStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMedicalAestheticsRoute = AdminMedicalAestheticsRouteImport.update({
  id: '/medical-aesthetics',
  path: '/medical-aesthetics',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/facesim': typeof FacesimRoute
  '/login': typeof LoginRoute
  '/poster-gen': typeof PosterGenRoute
  '/admin/medical-aesthetics': typeof AdminMedicalAestheticsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/facesim': typeof FacesimRoute
  '/login': typeof LoginRoute
  '/poster-gen': typeof PosterGenRoute
  '/admin/medical-aesthetics': typeof AdminMedicalAestheticsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/facesim': typeof FacesimRoute
  '/login': typeof LoginRoute
  '/poster-gen': typeof PosterGenRoute
  '/admin/medical-aesthetics': typeof AdminMedicalAestheticsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/stats': typeof AdminStatsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/facesim'
    | '/login'
    | '/poster-gen'
    | '/admin/medical-aesthetics'
    | '/admin/models'
    | '/admin/providers'
    | '/admin/stats'
    | '/admin/users'
    | '/dashboard/chat'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/facesim'
    | '/login'
    | '/poster-gen'
    | '/admin/medical-aesthetics'
    | '/admin/models'
    | '/admin/providers'
    | '/admin/stats'
    | '/admin/users'
    | '/dashboard/chat'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/facesim'
    | '/login'
    | '/poster-gen'
    | '/admin/medical-aesthetics'
    | '/admin/models'
    | '/admin/providers'
    | '/admin/stats'
    | '/admin/users'
    | '/dashboard/chat'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  FacesimRoute: typeof FacesimRoute
  LoginRoute: typeof LoginRoute
  PosterGenRoute: typeof PosterGenRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/poster-gen': {
      id: '/poster-gen'
      path: '/poster-gen'
      fullPath: '/poster-gen'
      preLoaderRoute: typeof PosterGenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facesim': {
      id: '/facesim'
      path: '/facesim'
      fullPath: '/facesim'
      preLoaderRoute: typeof FacesimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/stats': {
      id: '/admin/stats'
      path: '/stats'
      fullPath: '/admin/stats'
      preLoaderRoute: typeof AdminStatsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/medical-aesthetics': {
      id: '/admin/medical-aesthetics'
      path: '/medical-aesthetics'
      fullPath: '/admin/medical-aesthetics'
      preLoaderRoute: typeof AdminMedicalAestheticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminMedicalAestheticsRoute: typeof AdminMedicalAestheticsRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminStatsRoute: typeof AdminStatsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminMedicalAestheticsRoute: AdminMedicalAestheticsRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminStatsRoute: AdminStatsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  FacesimRoute: FacesimRoute,
  LoginRoute: LoginRoute,
  PosterGenRoute: PosterGenRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
